food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('<int:pk>/', views.ItemDetailView.as_view(),name='detail'),
    path('item/', views.item, name='item'),
    path('add/', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:item_id>', views.update_item, name='update_item'),
    path('delete/<int:item_id>', views.delete_item, name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilePage, name='profile'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://p.kindpng.com/picc/s/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.

# def index(request):
#     item_list = Item.objects.all()
#     context = {
#         'item_list': item_list,
#     }
#     return render(request, 'food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name = "food/index.html"
    context_object_name = 'item_list'

def item(request):
    return HttpResponse('<h2>This is an item view</h2>')

# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item':item,
#     }
#     return render(request, 'food/detail.html', context)

class ItemDetailView(DetailView):
    model = Item
    template_name = 'food/detail.html'


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_description', 'item_price', 'item_image']
    template_name = 'food/item-form.html'
    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)
    

def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form':form, 'item':item})

def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'food/item-delete.html', {'item':item})
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}!')
            return redirect('login')
    form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})

@login_required
def profilePage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Food App</title>
        <link rel="stylesheet" href="{% static 'food/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand">Food App</a>
        <div class="navbar">
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Item</a>
            <a href="#" class="nav-item nav-link">Delete Item</a>
            <a href="" class="nav-item nav-link">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}

    {% block body %}

    {% endblock %}

</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img class="card" height="300px" src={{object.item_image}}>
            </div>
            <div class="col-md-6">
                <h1>{{  object.item_name }}</h1>
                <h2>{{  object.item_desc }}</h2>
                <h3>${{  object.item_price }}</h3>
                <a href="{% url 'food:delete_item' object.id %}">Delete</a>
            </div>
        </div>
    </div>

    
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">

<body>

    {% block body %}

        {% for item in item_list %}
            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img class="card" height="150px" src={{ item.item_image }} alt="">
                </div>
                <div class="col-md-4">
                    <h3>{{ item.item_name }}</h3>
                    <h5>{{ item.item_description }}</h5>
                    <h6>${{ item.item_price }}</h6>
                    <h6>${{ item.user_name }}</h6>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
                    <a href="{% url 'food:update_item' item.id %}" class="btn btn-warning">Update</a>
                </div>
            </div>
        {% endfor %}

    {% endblock %}

</body>
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}?</h2>
    {{ form }}
    <button type="submit">Confirm</button>
</form>
{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

users/templates/users/logout.html
<h1>You have been logged out.</h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src='{{ user.profile.image.url }}' height='400'>
<h1>{{ user.profile.location }}</h1>

users/templates/users/register.html
<form method='POST'>
    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>
</form>